"""add organ_name to companies

Revision ID: 2662059b1877
Revises: 21fe6fecd971
Create Date: 2025-07-07 02:27:02.254344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2662059b1877'
down_revision: Union[str, Sequence[str], None] = '21fe6fecd971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('organ_name', sa.String(length=255), nullable=True))
    op.alter_column('companies', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('companies', 'organ_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('companies', 'organ_short_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_companies_organ_name'), 'companies', ['organ_name'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_companies_organ_name'), table_name='companies')
    op.alter_column('companies', 'organ_short_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('companies', 'organ_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('companies', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('companies', 'organ_name')
    # ### end Alembic commands ###
